POST http://127.0.0.1:8000/register HTTP/1.1
content-type: application/json

{
  "first_name_register": "firstname",
  "middle_name_register": "midname",
  "last_name_register": "lastname",
  "job_title_register": "aircraft manual",
  "enterprise_name": "PTDI",
  "email_register": "testd@example.com",
  "password_register": "password",
  "password_register_confirmation": "password"
}

###


###POST http://127.0.0
.1:8000/api/login HTTP/1.1
Content-Type: application/json
X-DEVICE-NAME: http_client

{
  "email": "luffy@example.com",
  "password": "password"
}

###

GET http://127.0.0.1:8000/api/s1000d/all HTTP/1.1
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer 2|f9eTaMj4prk1BkhXiUshHssoLJeOhcL42fBYfbbT870fc934

###


###

POST http://127.0.0.1:8000/api/s1000d/csdb/update/foo.xml HTTP/1.1
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer 2|f9eTaMj4prk1BkhXiUshHssoLJeOhcL42fBYfbbT870fc934