POST http://127.0.0.1:8000/register HTTP/1.1
content-type: application/json

{
  "first_name_register": "firstname",
  "middle_name_register": "midname",
  "last_name_register": "lastname",
  "job_title_register": "aircraft manual",
  "enterprise_name": "PTDI",
  "email_register": "testd@example.com",
  "password_register": "password",
  "password_register_confirmation": "password"
}

###


###POST http://127.0.0
# untuk luffy Bearer 3|xEyVnL2vDEgHL3OA086YnvrUwKiuhwQLAj3S7BtFf22e4e44
# untuk nami Bearer 11|AjSqzL75J0HAK0iZTwdJm9RLTb7DYIo2n3evpOgY3e7344e4
POST http://127.0.0.1:8000/api/login HTTP/1.1
Content-Type: application/json
X-Requested-With: XMLHttpRequest
X-DEVICE-NAME: http_client

{
  "email": "nami@example.com",
  "password": "password"
}

###

POST http://127.0.0.1:8000/api/auth-check HTTP/1.1
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer 3|xEyVnL2vDEgHL3OA086YnvrUwKiuhwQLAj3S7BtFf22e4e44

###

GET http://127.0.0.1:8000/api/s1000d/csdb/all HTTP/1.1
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer 3|xEyVnL2vDEgHL3OA086YnvrUwKiuhwQLAj3S7BtFf22e4e44

###

POST http://127.0.0.1:8000/api/s1000d/csdb/update/foo.xml HTTP/1.1
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer 3|xEyVnL2vDEgHL3OA086YnvrUwKiuhwQLAj3S7BtFf22e4e44

###
# GET http://127.0.0.1:8000/api/s1000d/folder/index?sc=path::csdb HTTP/1.1
# GET http://127.0.0.1:8000/api/s1000d/path/{path} , setiap slash "/" pada path harus direplace dengan underscores
# GET http://127.0.0.1:8000/api/s1000d/path/csdb%2F HTTP/1.1
# GET http://127.0.0.1:8000/api/s1000d/path/csdb/amm?sc=DMC-&stt=act HTTP/1.1

GET http://127.0.0.1:8000/api/s1000d/path/csdb/dmc HTTP/1.1
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer 3|xEyVnL2vDEgHL3OA086YnvrUwKiuhwQLAj3S7BtFf22e4e44

###

POST http://127.0.0.1:8000/api/s1000d/csdb/create HTTP/1.1
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer 3|xEyVnL2vDEgHL3OA086YnvrUwKiuhwQLAj3S7BtFf22e4e44

{
  "tes" : "tesas",
  "xmleditor" : "axaasss"
}

###

GET http://127.0.0.1:8000/api/s1000d/ident/DML-MALE-0001Z-P-2024-00002_000-01.xml HTTP/1.1
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer 3|xEyVnL2vDEgHL3OA086YnvrUwKiuhwQLAj3S7BtFf22e4e44

###

GET http://127.0.0.1:8000/api/s1000d/status/COM-MALE-0001Z-Q-2024-00500_EN-EN.xml HTTP/1.1
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer 3|xEyVnL2vDEgHL3OA086YnvrUwKiuhwQLAj3S7BtFf22e4e44

###

GET http://127.0.0.1:8000/api/s1000d/histories/COM-MALE-0001Z-Q-2024-00500_EN-EN.xml HTTP/1.1
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer 3|xEyVnL2vDEgHL3OA086YnvrUwKiuhwQLAj3S7BtFf22e4e44

###
# GET http://127.0.0.1:8000/api/s1000d/comments/COM-MALE-0001Z-Q-2024-00500_EN-EN.xml HTTP/1.1
# GET http://127.0.0.1:8000/api/s1000d/comments/DDN-MALE-0001Z-0001Z-2024-00001.xml?access_key=oQULMZKQJ+V0hlXTxNp3uw==::03a910460a2b300c0aaf03d0aabfaeab HTTP/1.1


GET http://127.0.0.1:8000/api/s1000d/comments/DMC-MALE-A-00-00-00-00A-00PA-D_000-02_EN-EN.xml?access_key=kZBDbwtfrSnSeK%2BX8Agmtg%3D%3D%3A%3Ad3dd3257d525554efb0b2cc5284cd906 HTTP/1.1
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer 6|sqvYHOhNPKFbq12FtKdjLPuQFJ4BJKX7sDo02Bgz32bbc1b8

###

GET http://127.0.0.1:8000/api/s1000d/ident/DMC-AKS-A-93-77-8000-05C-539C-B_000-01_EN-US.xml HTTP/1.1
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer 3|xEyVnL2vDEgHL3OA086YnvrUwKiuhwQLAj3S7BtFf22e4e44

###
# Authorization: Bearer 3|xEyVnL2vDEgHL3OA086YnvrUwKiuhwQLAj3S7BtFf22e4e44

GET http://127.0.0.1:8000/api/s1000d/csdb/dispatched HTTP/1.1
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer 5|4As7LAvvQTXbQEBFjQeuJU2QyTW245w4pZc3JTpc617309fa

###

GET http://127.0.0.1:8000/api/s1000d/csdb/all HTTP/1.1
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer 3|xEyVnL2vDEgHL3OA086YnvrUwKiuhwQLAj3S7BtFf22e4e44

###

GET http://127.0.0.1:8000/api/s1000d/path/CSDB/DDN HTTP/1.1
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer 3|xEyVnL2vDEgHL3OA086YnvrUwKiuhwQLAj3S7BtFf22e4e44

###
# GET http://127.0.0.1:8000/api/s1000d/csdb/read/DDN-MALE-0001Z-0001Z-2024-00001.xml?form=json HTTP/1.1

GET http://127.0.0.1:8000/api/s1000d/csdb/read/IMF-0001Z-00012-001-01_000-01.xml?form=html&user_access_key=iXZL8T1KyEiUlcWacED%2FCg%3D%3D%3A%3A5d0d9dae37277e3f3063412ae9d3c74b HTTP/1.1
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer 3|xEyVnL2vDEgHL3OA086YnvrUwKiuhwQLAj3S7BtFf22e4e44

###

GET http://127.0.0.1:8000/api/s1000d/user/search HTTP/1.1
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer 3|xEyVnL2vDEgHL3OA086YnvrUwKiuhwQLAj3S7BtFf22e4e44

###

GET http://127.0.0.1:8000/api/s1000d/dml/DML-MALE-0001Z-P-2024-00001_000-01.xml?form=json&complete=0 HTTP/1.1
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer 9|iuuE4q042tzM9vzOYIY5kKpfXhviEhjGxb7JHhfx17244b63

###

GET http://127.0.0.1:8000/api/s1000d/csdb/read/DMC-MALE-A-15-00-01-00A-018A-A_000-01_EN-EN.xml?form=pdf HTTP/1.1
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Authorization: Bearer 9|iuuE4q042tzM9vzOYIY5kKpfXhviEhjGxb7JHhfx17244b63